def chatbot_response(user_input):
    # Predefined rules and responses
    rules = {
        "hi": "Hello! How can I assist you today?",
        "how are you": "I'm just a chatbot, but thanks for asking!",
        "bye": "Goodbye! Have a great day!",
        "what is your name": "I'm just a chatbot, so I don't have a name.",
        "what time is it": "Sorry, I cannot provide real-time information.",
        "who created you": "I was created by OpenAI.",
        "where are you from": "I'm a virtual assistant, so I don't have a physical location.",
        "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
        "how old are you": "I'm just a program, so I don't have an age.",
        "what is the meaning of life": "The meaning of life is subjective and varies from person to person.",
        "what can you do": "I can provide information, answer questions, or just have a chat with you.",
        "tell me about yourself": "I'm a chatbot designed to assist users with their queries.",
        "do you like pizza": "I don't have taste buds, so I can't enjoy pizza.",
        "what's your favorite color": "I don't have preferences like humans do.",
        "can you help me": "Yes, I'll do my best to assist you!",
        "are you human": "No, I'm an artificial intelligence.",
        "what languages do you speak": "I can communicate in any language you prefer.",
        "are you intelligent": "I'm programmed to respond intelligently, but I don't possess human-like intelligence.",
        "how do I contact support": "Please visit our website for support contact information.",
        "what is the weather today": "I'm sorry, I cannot provide real-time weather information.",
        "can you tell me a story": "Once upon a time, in a faraway land...",
        "who is your favorite superhero": "I don't have personal preferences.",
        "what's the capital of France": "The capital of France is Paris.",
        "how do I reset my password": "Please follow the password reset instructions on our website.",
        "what's the latest news": "You can check the latest news on any news website or app.",
        "what's your favorite book": "I don't have the ability to read or enjoy books.",
        "can you do my homework": "I'm here to provide assistance, but I cannot do your homework for you.",
        "what's the tallest mountain in the world": "Mount Everest is the tallest mountain in the world.",
        "what's your favorite movie": "As an AI, I don't have personal preferences like humans.",
        "do you dream": "I'm not capable of dreaming.",
        "how do I cook pasta": "You can find many recipes online for cooking pasta.",
        "tell me something interesting": "Did you know that the shortest war in history lasted only 38 minutes?",
        "can you recommend a restaurant": "I can provide restaurant recommendations based on your preferences.",
        "what is the population of Japan": "The population of Japan is approximately 126.3 million people.",
        "what's your favorite song": "I don't have the ability to listen to or enjoy music.",
        "can you translate this for me": "Yes, I can help with translation. Please provide the text.",
        "how do I get to the nearest bank": "You can use a maps application to find the nearest bank.",
        "what's the largest ocean": "The Pacific Ocean is the largest ocean in the world.",
        "tell me a fun fact": "Did you know that the first oranges weren't orange?",
        "can you do magic": "I'm not capable of performing magic tricks.",
        "what is the speed of light": "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
        "do you have any pets": "I don't have physical form or needs like pets do.",
        "what's the meaning of AI": "AI stands for Artificial Intelligence, which refers to machines or systems that mimic human intelligence.",
        "do you believe in aliens": "As an AI, I don't hold beliefs like humans do.",
        "what is the capital of Australia": "The capital of Australia is Canberra.",
        "can you sing": "I'm not capable of singing.",
        "what's your favorite animal": "I don't have preferences like humans do.",
        "what's the distance to the moon": "The average distance from Earth to the Moon is about 384,400 kilometers.",
        "can you tell me a riddle": "Sure! What has keys but can't open locks? A piano!",
        "how do I learn programming": "You can start by learning the basics of a programming language through online tutorials or courses.",
        "what's the square root of 144": "The square root of 144 is 12.",
        "do you play video games": "I don't have the ability to play video games.",
        "what's the capital of Canada": "The capital of Canada is Ottawa.",
        "can you tell me a tongue twister": "Sure! How about this one: She sells seashells by the seashore.",
        "how do I make a sandwich": "You can make a sandwich by assembling your favorite ingredients between two slices of bread.",
        "what's the largest desert in the world": "The largest desert in the world is the Sahara Desert.",
        "tell me a scary story": "Once upon a time, in a dark forest...",
        "what's the temperature in New York": "I'm sorry, I cannot provide real-time temperature information.",
        "do you believe in ghosts": "As an AI, I don't hold beliefs like humans do.",
        "what's the diameter of the Earth": "The diameter of the Earth is approximately 12,742 kilometers.",
        "what's the meaning of love": "Love is a complex emotion that can mean different things to different people.",
        "can you tell me a poem": "Sure! Roses are red, violets are blue, sugar is sweet, and so are you.",
        "how do I tie a tie": "You can find step-by-step instructions for tying a tie online.",
        "what's the smallest country in the world": "The smallest country in the world is Vatican City.",
        "tell me a science fact": "Did you know that a single bolt of lightning contains enough energy to toast 100,000 slices of bread?",
        "what's the largest planet in the solar system": "The largest planet in the solar system is Jupiter.",
        "do you know any jokes": "Sure! Why couldn't the bicycle stand up by itself? It was two-tired!",
        "what's the longest river in the world": "The longest river in the world is the Nile River.",
        "tell me a quote": "Here's a quote by Albert Einstein: 'Imagination is more important than knowledge.'",
        "what's the capital of Brazil": "The capital of Brazil is Brasília.",
        "can you do a backflip": "I'm just a virtual assistant, so I don't have a physical form to perform a backflip.",
        "what's the speed of sound": "The speed of sound varies depending on factors like temperature and altitude, but it's approximately 343 meters per second in dry air at 20 degrees Celsius.",
        "do you like ice cream": "I don't have taste buds, so I don't have preferences like humans do.",
        "what's the meaning of happiness": "Happiness is a subjective emotion that can be defined differently by each individual.",
        "can you do a handstand": "I'm just a virtual assistant, so I don't have a physical form to perform a handstand.",
        "what's the capital of China": "The capital of China is Beijing.",
        "can you solve a Rubik's Cube": "I'm not capable of solving physical puzzles like a Rubik's Cube.",
        "what's the temperature of the sun": "The temperature of the sun's surface is about 5,500 degrees Celsius.",
        "do you know any magic tricks": "I'm not capable of performing magic tricks.",
        "what's the largest country in the world": "The largest country in the world by land area is Russia.",
        "tell me a random fact": "Did you know that the shortest war in history lasted only 38 minutes?",
        "what's the distance to the nearest star": "The nearest star to Earth, besides the Sun, is Proxima Centauri, which is about 4.24 light-years away.",
        "do you like chocolate": "I don't have taste buds, so I don't have preferences like humans do.",
        "what's the meaning of success": "Success can be defined differently by each person and often involves achieving goals or fulfilling one's desires.",
        "can you tell me a myth": "Sure! How about the myth of Pandora's Box?",
        "what's the capital of India": "The capital of India is New Delhi.",
        "do you know any tongue twisters": "Sure! How about this one: How can a clam cram in a clean cream can?",
        "what's the diameter of the sun": "The diameter of the sun is about 1.4 million kilometers.",
        "tell me a historical fact": "Did you know that the Great Wall of China is over 13,000 miles long?",
        "what's the largest animal in the world": "The blue whale is the largest animal in the world.",
        "can you tell me a bedtime story": "Once upon a time, in a land far, far away...",
        "what's the meaning of friendship": "Friendship is a close relationship between two or more people based on mutual affection and trust.",
        "can you tell me a fun joke": "Sure! Why don't skeletons fight each other? They don't have the guts!",
        "what's the capital of South Africa": "The capital of South Africa is Pretoria, although the legislative capital is Cape Town and the judicial capital is Bloemfontein.",
        "do you know any good recipes": "Yes, I can provide you with recipes. What type of recipe are you looking for?",
        "what's the temperature of boiling water": "The temperature of boiling water at sea level is 100 degrees Celsius or 212 degrees Fahrenheit.",
        "can you tell me a fairy tale": "Sure! How about the tale of Cinderella?",
        "what's the smallest planet in the solar system": "The smallest planet in the solar system is Mercury.",
        "do you like cookies": "I don't have taste buds, so I don't have preferences like humans do.",
        "what's the meaning of freedom": "Freedom is the power or right to act, speak, or think as one wants without hindrance or restraint.",
        "can you tell me a fact about space": "Sure! Did you know that a day on Venus is longer than a year on Venus?",
        "what's the capital of Japan": "The capital of Japan is Tokyo.",
        "do you know any magic": "I'm not capable of performing magic tricks.",
        "what's the temperature of the human body": "The average normal body temperature for humans is around 98.6 degrees Fahrenheit or 37 degrees Celsius.",
        "can you tell me a joke about computers": "Sure! Why was the computer cold? It left its Windows open!",
        "what's the tallest building in the world": "As of my last update, the tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.",
        "tell me a space fact": "Sure! Did you know that there are more stars in the universe than grains of sand on all the beaches on Earth?",
        "what's the capital of Italy": "The capital of Italy is Rome.",
        "can you tell me a joke about food": "Sure! Why did the tomato turn red? Because it saw the salad dressing!",
        "what's the temperature of the ocean": "Ocean temperatures vary depending on location, depth, and season, but they generally range from around freezing to over 30 degrees Celsius (86 degrees Fahrenheit) in tropical regions.",
        "do you like to dance": "I don't have a physical form, so I can't dance.",
        "what's the largest moon in the solar system": "The largest moon in the solar system is Ganymede, which orbits Jupiter.",
        "can you tell me a joke about animals": "Sure! Why don't fish play piano? Because you can't tuna fish!",
        "what's the meaning of technology": "Technology refers to the application of scientific knowledge for practical purposes, especially in industry.",
        "can you tell me a joke about school": "Sure! Why did the math book look sad? Because it had too many problems!",
        "what's the capital of Russia": "The capital of Russia is Moscow.",
        "do you know any magic tricks": "I'm not capable of performing magic tricks.",
        "what's the temperature of the Arctic": "Arctic temperatures vary widely depending on the season and location, but they can range from about -40 degrees Celsius in winter to just above freezing in summer.",
        "can you tell me a joke about money": "Sure! Why did the coin go to school? Because it wanted to be smart!",
        "what's the highest mountain in Africa": "The highest mountain in Africa is Mount Kilimanjaro, located in Tanzania.",
        "tell me a funny joke": "Sure! Why don't scientists trust atoms? Because they make up everything!",
        "what's the temperature of Antarctica": "Antarctica is the coldest place on Earth, with temperatures commonly dropping below -50 degrees Celsius (-58 degrees Fahrenheit) in winter.",
        "can you tell me a joke about doctors": "Sure! Why did the doctor carry a red pen? In case they needed to draw blood!",
        "what's the fastest animal on land": "The fastest animal on land is the cheetah, which can reach speeds of up to 70 miles per hour (113 kilometers per hour) in short bursts covering distances up to 500 meters.",
        "what's the highest mountain in North America": "The highest mountain in North America is Denali, also known as Mount McKinley, located in Alaska, United States.",
        "can you tell me a joke about the internet": "Sure! Why was the math book sad? Because it had too many problems!",
        "what's the meaning of science": "Science is the systematic study of the structure and behavior of the physical and natural world through observation and experiment.",
        "can you tell me a joke about space": "Sure! How does the solar system keep its pants up? With an asteroid belt!",
        "what's the temperature of the Sahara Desert": "The Sahara Desert is one of the hottest places on Earth, with temperatures commonly exceeding 50 degrees Celsius (122 degrees Fahrenheit) during the day and dropping below freezing at night.",
        "what's the largest lake in the world": "The largest lake in the world by surface area is the Caspian Sea, located between Europe and Asia.",
        "can you tell me a joke about time": "Sure! Why don't skeletons fight each other? They don't have the guts!",
        "what's the highest mountain in South America": "The highest mountain in South America is Mount Aconcagua, located in the Andes mountain range in Argentina.",
        "tell me a joke about cars": "Sure! Why did the car's engine stop? Because it had gas!",
        "what's the smallest ocean in the world": "The smallest ocean in the world is the Arctic Ocean.",
        "can you tell me a joke about plants": "Sure! Why was the plant's report card so bad? It was always cutting class!",
        "what's the meaning of art": "Art is a diverse range of human activities and creations that express ideas, emotions, and experiences through visual, auditory, or performance mediums.",
        "can you tell me a joke about the future": "Sure! Why did the smartphone go to therapy? Because it had too many issues!",
        "what's the deepest ocean in the world": "The deepest ocean in the world is the Pacific Ocean's Mariana Trench, which reaches a depth of approximately 36,070 feet (10,994 meters).",
        "tell me a joke about electricity": "Sure! Why was the math book sad? Because it had too many problems!",
        "what's the capital of Egypt": "The capital of Egypt is Cairo.",
        "can you tell me a joke about the environment": "Sure! Why did the tree go to the dentist? It needed a root canal!",
        "what's the meaning of life": "The meaning of life is subjective and varies from person to person.",
        "what's the tallest mountain in Asia": "The tallest mountain in Asia and the world is Mount Everest, located in the Himalayas on the border between Nepal and China.",
        "tell me a joke about food": "Sure! Why did the tomato turn red? Because it saw the salad dressing!",
        "what's the fastest bird in the world": "The fastest bird in the world is the peregrine falcon, which can reach speeds of over 240 miles per hour (386 kilometers per hour) when diving.",
        "can you tell me a joke about the weather": "Sure! Why did the weather report go to school? To get a little brighter!",
        "what's the meaning of education": "Education is the process of facilitating learning, or the acquisition of knowledge, skills, values, beliefs, and habits.",
        "tell me a joke about math": "Sure! Why was the math book sad? Because it had too many problems!",
        "what's the capital of France": "The capital of France is Paris."
    }

    # Convert input to lowercase for case-insensitive matching
    user_input = user_input.lower()

    # Check if user input matches any predefined rule
    for pattern, response in rules.items():
        if pattern in user_input:
            return response
    
    # If no predefined rule matches, return default response
    return rules["default"]

# Main loop
print("Welcome! Type 'bye' to exit.")
while True:
    user_input = input("You: ")
    if user_input.lower() == "bye":
        print(chatbot_response(user_input))
        break
    else:
        print("Bot:", chatbot_response(user_input))
